include ../Makefile.tests_common

# USEMODULE += hashes
# USEMODULE += hashes_sw_sha1
# USEMODULE += hashes_sw_sha256
# USEMODULE += hashes_sha256
# USEMODULE += hashes_sha2xx_common
# USEMODULE += hashes_sha1

# USEMODULE += psa_crypto
# USEMODULE += fmt

# FEATURES_REQUIRED += periph_flashpage
# FEATURES_OPTIONAL += periph_flashpage_pagewise
USEPKG += psa-arch-tests

# export TEST_KCONFIG ?= 1

# ARCHIVES += /home/lena/Dokumente/work/repos/psa-arch-tests/api-tests/BUILD/dev_apis/crypto/test_combine.a

# ARCHIVES += /home/lena/Dokumente/work/repos/psa-arch-tests/api-tests/BUILD/val/val_nspe.a

# ARCHIVES += /home/lena/Dokumente/work/repos/psa-arch-tests/api-tests/BUILD/platform/pal_nspe.a

include $(RIOTBASE)/Makefile.include
